// Code generated by reset generator. DO NOT EDIT.

package server

func (s *ServerConfig) Reset() {
	if s == nil {
		return
	}

	s.Addr = ""

	s.LogMode = ""

	s.StoreInterval = 0

	s.FileStoragePath = ""

	s.Restore = false

	s.DatabaseDSN = ""

	s.AuditFile = ""

	s.AuditURL = ""
}
