package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

// FieldInfo описывает одно поле структуры для генерации кода сброса
type FieldInfo struct {
	Name    string
	Kind    FieldKind
	ZeroVal string // для примитивов — их нулевое значение
}

// FieldKind — тип поля
type FieldKind int

const (
	KindPrimitive FieldKind = iota // int, string, bool, float64, …
	KindSlice                      // []T
	KindMap                        // map[K]V
	KindPointer                    // *T (включая *struct)
	KindStruct                     // встроенная структура (значением, не указателем)
)

// StructInfo — всё, что нужно для генерации одного метода Reset()
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

// PackageInfo — данные одного пакета: имя, путь к директории и список структур
type PackageInfo struct {
	PackageName string
	Dir         string
	Structs     []StructInfo
}

// resetTemplate — шаблон для генерируемого файла reset.gen.go
var resetTemplate = template.Must(template.New("reset").Funcs(template.FuncMap{
	"isZero":   func(k FieldKind) bool { return k == KindPrimitive },
	"isSlice":  func(k FieldKind) bool { return k == KindSlice },
	"isMap":    func(k FieldKind) bool { return k == KindMap },
	"isPtr":    func(k FieldKind) bool { return k == KindPointer },
	"isStruct": func(k FieldKind) bool { return k == KindStruct },
}).Parse(`// Code generated by reset generator. DO NOT EDIT.

package {{ .PackageName }}
{{ range .Structs }}
func (s *{{ .Name }}) Reset() {
	if s == nil {
		return
	}
{{ range .Fields }}{{ if isZero .Kind }}
	s.{{ .Name }} = {{ .ZeroVal }}
{{ else if isSlice .Kind }}
	s.{{ .Name }} = s.{{ .Name }}[:0]
{{ else if isMap .Kind }}
	clear(s.{{ .Name }})
{{ else if isPtr .Kind }}
	if s.{{ .Name }} != nil {
		if resetter, ok := any(s.{{ .Name }}).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*s.{{ .Name }} = *new({{ .ZeroVal }})
		}
	}
{{ else if isStruct .Kind }}
	if resetter, ok := any(&s.{{ .Name }}).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		s.{{ .Name }} = *new({{ .ZeroVal }})
	}
{{ end }}{{ end }}}
{{ end }}
`))

func main() {
	// Паттерн для загрузки пакетов: первый аргумент или ./...
	pattern := "./..."
	if len(os.Args) > 1 {
		pattern = os.Args[1]
	}

	// packages.Load загружает все пакеты, учитывая build tags и go.mod.
	// В отличие от parser.ParseDir, правильно обрабатывает build constraints
	// и корректно ассоциирует файлы с пакетами.
	//
	// NeedName   — имя пакета (pkg.Name)
	// NeedFiles  — пути к .go-файлам (GoFiles), нужны для определения директории
	// NeedSyntax — распарсенные AST-деревья с комментариями (pkg.Syntax)
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax,
		Tests: false, // исключаем тестовые пакеты (_test suffix)
		// ParseFile — кастомный парсер: пропускаем уже сгенерированные файлы
		// прямо на этапе загрузки, до построения AST.
		// Сигнатура func(fset, filename, src) совместима с parser.ParseFile
		// при фиксированном режиме (ParseComments).
		ParseFile: func(fset *token.FileSet, filename string, src []byte) (*ast.File, error) {
			if strings.HasSuffix(filename, ".gen.go") {
				// Возвращаем пустой файл — packages пропустит его синтаксис,
				// но путь останется в GoFiles (это нормально)
				return parser.ParseFile(fset, filename, []byte("package _"), parser.ParseComments)
			}
			return parser.ParseFile(fset, filename, src, parser.ParseComments)
		},
	}

	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		fmt.Fprintf(os.Stderr, "load error: %v\n", err)
		os.Exit(1)
	}

	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	generated := 0
	for _, pkg := range pkgs {
		info := extractPackageInfo(pkg)
		if info == nil || len(info.Structs) == 0 {
			continue
		}

		outFile := filepath.Join(info.Dir, "reset.gen.go")
		if err := generateFile(outFile, info); err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", outFile, err)
			continue
		}
		fmt.Printf("generated %s (%d struct(s))\n", outFile, len(info.Structs))
		generated++
	}

	if generated == 0 {
		fmt.Println("no structures with // generate:reset found")
	}
}

// extractPackageInfo обходит все файлы пакета и собирает помеченные структуры.
// Директория пакета определяется из пути первого GoFile.
func extractPackageInfo(pkg *packages.Package) *PackageInfo {
	// Определяем директорию из GoFiles — они доступны при NeedFiles
	dir := ""
	for _, f := range pkg.GoFiles {
		if !strings.HasSuffix(f, ".gen.go") {
			dir = filepath.Dir(f)
			break
		}
	}
	if dir == "" {
		return nil
	}

	info := &PackageInfo{
		PackageName: pkg.Name,
		Dir:         dir,
	}

	for _, file := range pkg.Syntax {
		if file == nil {
			continue
		}
		// Пропускаем заглушки для .gen.go — у них имя пакета "_"
		if file.Name.Name == "_" {
			continue
		}
		structs := findMarkedStructs(file)
		info.Structs = append(info.Structs, structs...)
	}

	return info
}

// findMarkedStructs ищет в AST-файле структуры с комментарием // generate:reset
func findMarkedStructs(file *ast.File) []StructInfo {
	var result []StructInfo

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		if !hasGenerateResetComment(genDecl.Doc) {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			si := StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: extractFields(structType),
			}
			result = append(result, si)
		}
	}

	return result
}

// hasGenerateResetComment проверяет наличие // generate:reset в группе комментариев
func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

// extractFields анализирует поля структуры и возвращает FieldInfo для каждого
func extractFields(st *ast.StructType) []FieldInfo {
	var fields []FieldInfo

	for _, field := range st.Fields.List {
		// Встроенные (анонимные) поля без имени пропускаем
		if len(field.Names) == 0 {
			continue
		}

		kind, zeroVal := classifyExpr(field.Type)

		for _, name := range field.Names {
			fields = append(fields, FieldInfo{
				Name:    name.Name,
				Kind:    kind,
				ZeroVal: zeroVal,
			})
		}
	}

	return fields
}

// classifyExpr определяет тип выражения AST и возвращает (Kind, нулевое значение / имя типа)
func classifyExpr(expr ast.Expr) (FieldKind, string) {
	switch t := expr.(type) {

	case *ast.Ident:
		return classifyIdent(t.Name)

	case *ast.SelectorExpr:
		// Тип из другого пакета, например time.Time — считаем структурой
		return KindStruct, exprToString(expr)

	case *ast.StarExpr:
		// Указатель — берём имя базового типа для *new(T)
		return KindPointer, exprToString(t.X)

	case *ast.ArrayType:
		return KindSlice, ""

	case *ast.MapType:
		return KindMap, ""

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return KindPrimitive, "nil"
	}

	return KindPrimitive, "nil"
}

// classifyIdent определяет вид простого идентификатора
func classifyIdent(name string) (FieldKind, string) {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return KindPrimitive, "0"
	case "string":
		return KindPrimitive, `""`
	case "bool":
		return KindPrimitive, "false"
	default:
		// Неизвестный идентификатор — именованный тип (скорее всего структура)
		return KindStruct, name
	}
}

// exprToString превращает AST-выражение типа обратно в строку
func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + exprToString(t.Elt)
		}
		return "[...]" + exprToString(t.Elt)
	case *ast.MapType:
		return "map[" + exprToString(t.Key) + "]" + exprToString(t.Value)
	default:
		return "interface{}"
	}
}

// generateFile рендерит шаблон и записывает файл, форматируя через gofmt
func generateFile(path string, info *PackageInfo) error {
	var buf bytes.Buffer
	if err := resetTemplate.Execute(&buf, info); err != nil {
		return fmt.Errorf("template execute: %w", err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		// Сохраняем сырой вывод для отладки
		src = buf.Bytes()
		fmt.Fprintf(os.Stderr, "warning: gofmt failed for %s: %v\n", path, err)
	}

	return os.WriteFile(path, src, 0o644)
}
