// Code generated by reset generator. DO NOT EDIT.

package main

func (s *User) Reset() {
	if s == nil {
		return
	}

	s.ID = 0

	s.Name = ""

	s.Email = ""

	s.Active = false

	s.Score = 0

	s.Tags = s.Tags[:0]

	clear(s.Metadata)

	if s.Address != nil {
		if resetter, ok := any(s.Address).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*s.Address = *new(Address)
		}
	}

	if resetter, ok := any(&s.Profile).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		s.Profile = *new(Profile)
	}
}

func (s *Address) Reset() {
	if s == nil {
		return
	}

	s.Street = ""

	s.City = ""

	s.Country = ""

	if s.Zip != nil {
		if resetter, ok := any(s.Zip).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*s.Zip = *new(string)
		}
	}

	s.Coords = s.Coords[:0]
}
